import type { IAttestationFormExportLabels, IInfringementLetterExportLabels } from '../export-document-html.js';

// English labels for export tests; the application passes translated labels from the catalogues.
export const englishLetterExportLabels: IInfringementLetterExportLabels = {
    auditPeriod: 'Audit Period:',
    cardNumber: 'Card Number:',
    colAllowed: 'Limit',
    colDateTime: 'Date / Time',
    colDescription: 'Infringement Description',
    colExcess: 'Excess / Deficit',
    colMeasured: 'Measured',
    colNum: '#',
    colSeverity: 'Severity',
    date: 'Date',
    dateAndSignature: 'Date: _________________ Signature: _________________',
    driver: 'Driver:',
    driverAckText: 'I acknowledge receipt and review of this infringement summary.',
    driverExplanation: 'Driver Comments / Explanation of Exceptional Circumstances (Article 12 Reg. 561/2006):',
    driverSignature: 'Driver Signature',
    file: 'File:',
    generated: 'Date Generated:',
    managerSignature: 'Transport Operations Manager',
    qualification:
        'ESM Viewer calculation — not a certified legal assessment. Confirm important findings with a qualified specialist.',
    severityMinor: 'Minor',
    severityMostSerious: 'Most serious',
    severitySerious: 'Serious',
    severityVerySerious: 'Very serious',
    statement:
        'An analysis of your digital tachograph records has identified the following infringement(s) against the rules established under Regulation (EC) No 561/2006, Directive 2002/15/EC, and Regulation (EU) No 165/2014.',
    title: 'Driver Infringement Notification & Acknowledgment',
    totalInfringements: 'Total Infringements:',
    vehicle: 'Vehicle:',
    vin: 'VIN',
};

export const englishAttestationExportLabels: IAttestationFormExportLabels = {
    date: 'Date:',
    declareDriver: 'declare that the driver:',
    driverSignature: 'Signature of the driver:',
    footnote1: '(1) This form is available in electronic and printable versions at the following address: http://ec.europa.eu',
    footnote2: '(2) European Agreement concerning the Work of Crews of Vehicles engaged in International Road Transport.',
    footnote3: '*** Choose only one box',
    forPeriod: 'for the period:',
    item10_licence: '10. Driving licence or identity card or passport number:',
    item11_employmentDate: '11. who has started to work at the undertaking on (day/month/year):',
    item12_from: '12. from (hour/day/month/year):',
    item13_to: '13. to (hour/day/month/year):',
    item14_sickLeave: '14. was on sick leave***',
    item15_annualLeave: '15. was on annual leave***',
    item16_leaveOrRest: '16. was on leave or rest***',
    item17_outOfScope: '17. drove a vehicle exempted from the scope of Regulation (EC) 561/2006 or the AETR***',
    item18_otherWork: '18. performed other work than driving***',
    item19_available: '19. was available***',
    item1_undertaking: '1. Name of the undertaking:',
    item20_place: '20. Place:',
    item21_driverConfirm:
        '21. I, the driver, confirm that I have not been driving a vehicle falling under the scope of Regulation (EC) 561/2006 or the AETR during the period mentioned above.',
    item22_place: '22. Place:',
    item2_address: '2. Street address, postal code, city, country:',
    item3_tel: '3. Telephone number (including international prefix):',
    item4_fax: '4. Fax number (including international prefix):',
    item5_email: '5. E-mail address:',
    item6_name: '6. Name and first name:',
    item7_position: '7. Position in the undertaking:',
    item8_driverName: '8. Name and first name:',
    item9_birthDate: '9. Date of birth (day/month/year):',
    officialAnnex: 'ANNEX',
    officialInstruction:
        'To be filled in by typing and signed before a journey. To be kept with the original control device records wherever they are required to be kept',
    officialRegulation: '(REGULATION (EC) 561/2006 OR THE AETR) (2)',
    officialTitle: 'ATTESTATION OF ACTIVITIES (1)',
    officialWarning: 'FALSE ATTESTATIONS CONSTITUTE AN INFRINGEMENT',
    partUndertaking: 'Part to be filled in by the undertaking',
    signature: 'Signature:',
    undersigned: 'I, the undersigned:',
};
