export {
    createCardUse,
    createVehicleUnitUse,
    createVehicleUse,
    getOdometerDistance,
    isOdometerKilometres,
    type CardSlot,
    type ICardUse,
    type ICardUseInput,
    type InsertedCardType,
    type IVehicleUnitUse,
    type IVehicleUnitUseInput,
    type IVehicleUse,
    type IVehicleUseInput,
    type OdometerKilometres,
    type TachographAssociation,
} from './association.js';
export {
    ACTIVITY_KINDS,
    calculateActivityTotals,
    classifyActivityIntervalRelation,
    compareActivityIntervals,
    createRecordedActivityInterval,
    createUnknownActivityGap,
    groupActivityDays,
    normalizeActivityDay,
    orderActivityIntervals,
    sumActivityTotals,
    UNKNOWN_CREW_CONTEXT,
    type ActivityDayNormalization,
    type ActivityInterval,
    type ActivityIntervalRelation,
    type ActivityKind,
    type ActivityTotalsCalculation,
    type ActivityTotalsSumCalculation,
    type CrewPresence,
    type IActivityCrewContext,
    type IActivityDay,
    type IActivityDayDurationOverflow,
    type IActivityDayEmptyData,
    type IActivityDayInvalidInterval,
    type IActivityDayInvalidMidnight,
    type IActivityDayMidnightBoundary,
    type IActivityDayNormalized,
    type IActivityDayOverlap,
    type IActivityTotals,
    type IActivityTotalsCalculated,
    type IActivityTotalsDurationOverflow,
    type IActivityTotalsInvalidInterval,
    type IActivityTotalsOverlap,
    type IInferredActivityGap,
    type IRecordedActivityInterval,
} from './activity.js';
export {
    createDocumentCapabilities,
    type DocumentCapability,
    type DocumentCapabilityFor,
    type DriverCardCapability,
    type IDocumentCapabilities,
    type SharedDocumentCapability,
    type VehicleUnitCapability,
} from './capability.js';
export {
    createAccumulatedDrivingPosition,
    createBorderCrossing,
    createDailyWorkPeriodPlace,
    createGnssPositionEvidence,
    createLoadTypeEntry,
    createLoadUnloadOperation,
    isGnssAccuracyIndicator,
    isGnssAuthenticationStatus,
    isLatitude,
    isLongitude,
    type DailyWorkPeriodEntryType,
    type DailyWorkPeriodRegion,
    type GnssAccuracyIndicator,
    type GnssAuthenticationStatus,
    type IAccumulatedDrivingPosition,
    type IAccumulatedDrivingPositionInput,
    type IBorderCrossing,
    type IBorderCrossingInput,
    type IDailyWorkPeriodPlace,
    type IDailyWorkPeriodPlaceInput,
    type IGeoCoordinates,
    type IGnssPositionEvidence,
    type IGnssPositionEvidenceInput,
    type ILoadTypeEntry,
    type ILoadTypeEntryInput,
    type ILoadUnloadOperation,
    type ILoadUnloadOperationInput,
    type IRecordedCardReference,
    type Latitude,
    type LoadTypeKind,
    type LoadUnloadOperationType,
    type Longitude,
    type TachographLocationRecord,
} from './location.js';
export {
    createCardNotes,
    createDriverIdentity,
    createVehicleIdentity,
    isCardNotesText,
    isCardNumber,
    isIdentityName,
    isIssuingMemberState,
    isRawMemberState,
    isVehicleIdentificationNumber,
    isVehicleRegistrationNumber,
    type CardNotesText,
    type CardNumber,
    type ICardNotes,
    type ICardNotesInput,
    type IdentityName,
    type IDriverIdentity,
    type IDriverIdentityInput,
    type IssuingMemberState,
    type RawMemberState,
    type RecordedIssuingMemberState,
    type IVehicleIdentity,
    type IVehicleIdentityInput,
    type TachographIdentity,
    type VehicleIdentificationNumber,
    type VehicleRegistrationNumber,
} from './identity.js';
export {
    createTachographEvent,
    createTachographFault,
    type EventFaultCode,
    type EventFaultRecordPurpose,
    type ITachographEvent,
    type ITachographEventInput,
    type ITachographFault,
    type ITachographFaultInput,
    type TachographEventFault,
} from './event-fault.js';
export {
    classifyChainVerifiedItems,
    classifyIntegrityItems,
    type IIntegrityChainVerified,
    type IIntegrityFailed,
    type IIntegrityInvalid,
    type IIntegrityNotChecked,
    type IIntegrityPartiallyValid,
    type IIntegrityUnsupported,
    type IIntegrityValid,
    type IntegrityAssessment,
    type IntegrityChainStatus,
    type IntegrityFailureCode,
    type IntegrityItem,
    type IntegrityItemStatus,
    type IntegrityNotCheckedReason,
    type VerificationGeneration,
    type VerificationLimitation,
    type VerifiedIntegrityAssessment,
} from './integrity.js';
export { createOverspeedRecord, type IOverspeedControlData, type IOverspeedRecord } from './overspeed.js';

export {
    decodeJsonPointerToken,
    encodeJsonPointerToken,
    isJsonPointer,
    readJsonPointerArrayIndex,
    type JsonPointer,
} from './json-pointer.js';
export { createSourceReference, type ISourceReference } from './source-reference.js';
export {
    createDetailedSpeedSample,
    isSpeedKilometresPerHour,
    type IDetailedSpeedSample,
    type IDetailedSpeedSampleInput,
    type SpeedKilometresPerHour,
} from './speed.js';
export { type CardGeneration, type DocumentKind, type TachographGeneration } from './tachograph.js';
export {
    createCardApplicationTechnicalData,
    createCardApplicationV2TechnicalData,
    createCardChipTechnicalData,
    createCardControlActivityTechnicalRecord,
    createCardCurrentUsageTechnicalRecord,
    createCardDownloadTechnicalRecord,
    createCardIccTechnicalData,
    createDrivingLicenceTechnicalData,
    createSpecificConditionTechnicalRecord,
    createVehicleUnitCalibrationTechnicalRecord,
    createVehicleUnitCardSlotStatusTechnicalRecord,
    createVehicleUnitCompanyLockTechnicalRecord,
    createVehicleUnitControlActivityTechnicalRecord,
    createVehicleUnitDailyOdometerTechnicalRecord,
    createVehicleUnitDownloadActivityTechnicalRecord,
    createVehicleUnitDownloadPeriodTechnicalRecord,
    createVehicleUnitEmbeddedCardTechnicalRecord,
    createVehicleUnitEmbeddedCardSnapshotTechnicalRecord,
    createVehicleUnitGnssCoupledTechnicalRecord,
    createVehicleUnitIdentificationTechnicalRecord,
    createVehicleUnitItsConsentTechnicalRecord,
    createVehicleUnitPowerSupplyInterruptionTechnicalRecord,
    createVehicleUnitSensorPairedTechnicalRecord,
    createVehicleUnitSpecificConditionTechnicalRecord,
    createVehicleUnitTimeAdjustmentTechnicalRecord,
    isDrivingLicenceNumber,
    isTechnicalByte,
    isTechnicalHexIdentifier,
    isTechnicalText,
    isTechnicalUnsignedLong,
    isTechnicalUnsignedShort,
    type CalibrationPurpose,
    type CardControlActivityType,
    type DriverCardTechnicalRecord,
    type DrivingLicenceNumber,
    type ICardApplicationTechnicalData,
    type ICardApplicationTechnicalDataInput,
    type ICardApplicationV2TechnicalData,
    type ICardApplicationV2TechnicalDataInput,
    type ICardChipTechnicalData,
    type ICardChipTechnicalDataInput,
    type ICardControlActivityTechnicalRecord,
    type ICardControlActivityTechnicalRecordInput,
    type ICardCurrentUsageTechnicalRecord,
    type ICardCurrentUsageTechnicalRecordInput,
    type ICardDownloadTechnicalRecord,
    type ICardDownloadTechnicalRecordInput,
    type ICardEmbedderIdentification,
    type ICardExtendedSerialNumber,
    type ICardIccTechnicalData,
    type ICardIccTechnicalDataInput,
    type IDrivingLicenceTechnicalData,
    type IDrivingLicenceTechnicalDataInput,
    type ISpecificConditionTechnicalRecord,
    type ISpecificConditionTechnicalRecordInput,
    type SpecificConditionType,
    type TachographTechnicalRecord,
    type TechnicalHexIdentifier,
    type ITechnicalExtendedSerialNumber,
    type IVehicleUnitCalibrationTechnicalRecord,
    type IVehicleUnitCalibrationTechnicalRecordInput,
    type IVehicleUnitCardSlotStatusTechnicalRecord,
    type IVehicleUnitCardSlotStatusTechnicalRecordInput,
    type IVehicleUnitCompanyLockTechnicalRecord,
    type IVehicleUnitCompanyLockTechnicalRecordInput,
    type IVehicleUnitControlActivityTechnicalRecord,
    type IVehicleUnitControlActivityTechnicalRecordInput,
    type IVehicleUnitDailyOdometerTechnicalRecord,
    type IVehicleUnitDailyOdometerTechnicalRecordInput,
    type IVehicleUnitDownloadActivityTechnicalRecord,
    type IVehicleUnitDownloadActivityTechnicalRecordInput,
    type IVehicleUnitDownloadPeriodTechnicalRecord,
    type IVehicleUnitDownloadPeriodTechnicalRecordInput,
    type IVehicleUnitEmbeddedCardTechnicalRecord,
    type IVehicleUnitEmbeddedCardTechnicalRecordInput,
    type IVehicleUnitGnssCoupledTechnicalRecord,
    type IVehicleUnitGnssCoupledTechnicalRecordInput,
    type IVehicleUnitIdentificationTechnicalRecord,
    type IVehicleUnitIdentificationTechnicalRecordInput,
    type IVehicleUnitItsConsentTechnicalRecord,
    type IVehicleUnitItsConsentTechnicalRecordInput,
    type IVehicleUnitPowerSupplyInterruptionTechnicalRecord,
    type IVehicleUnitPowerSupplyInterruptionTechnicalRecordInput,
    type IVehicleUnitSensorPairedTechnicalRecord,
    type IVehicleUnitSensorPairedTechnicalRecordInput,
    type IVehicleUnitSpecificConditionTechnicalRecord,
    type IVehicleUnitSpecificConditionTechnicalRecordInput,
    type IVehicleUnitTimeAdjustmentTechnicalRecord,
    type IVehicleUnitTimeAdjustmentTechnicalRecordInput,
    type VehicleUnitTechnicalRecord,
} from './technical.js';
export {
    getUtcDuration,
    isDurationMilliseconds,
    isUtcTimestamp,
    nowAsUtcTimestamp,
    utcIntervalsOverlap,
    type DurationMilliseconds,
    type IUtcInterval,
    type UtcTimestamp,
} from './time.js';
export { createTachographWarning, type ITachographWarning, type TachographWarningCode } from './warning.js';
