import type { IAttestationFormPdfRequest, IInfringementLetterPdfRequest } from '#contracts';
import type { IAttestationFormViewModel } from './attestation-form-view-model.js';
import type { IAttestationFormExportLabels } from './export-document-html.js';
import type { IInfringementLetterViewModel } from './infringement-letter-view-model.js';
import type { IInfringementLetterExportLabels } from './export-document-html.js';

// Builds typed native PDF-engine request for driver infringement letter.
export function createInfringementLetterPdfRequest(
    model: IInfringementLetterViewModel,
    labels: IInfringementLetterExportLabels,
    severityLabel: (severity: 'minor' | 'mostSerious' | 'serious' | 'verySerious') => string,
    companyDetailsTitle: string,
    dateSignatureLabel: string,
    vinLabel: string,
    locale: string,
): IInfringementLetterPdfRequest {
    return {
        allowedHeader: labels.colAllowed,
        cardNumber: model.cardNumber,
        cardNumberLabel: labels.cardNumber,
        categoryHeader: labels.colDescription,
        companyAddress: model.company.address,
        companyDetailsTitle,
        companyName: model.company.companyName,
        datePrinted: model.generatedAt,
        datePrintedLabel: labels.generated,
        dateSignatureLabel,
        dateTimeHeader: labels.colDateTime,
        descriptionHeader: labels.colDescription,
        driverComments: model.driverExplanation,
        driverCommentsTitle: labels.driverExplanation,
        driverDeclarationText: labels.driverAckText,
        driverDetailsTitle: labels.driver,
        driverName: model.driverName,
        driverNameLabel: labels.driver,
        driverSignatureLabel: labels.driverSignature,
        excessHeader: labels.colExcess,
        fileLabel: labels.file,
        fileName: model.fileName,
        footerNotice: labels.qualification,
        infringements: model.items.map((item, index) => ({
            allowed: item.allowedValue,
            category: item.title,
            dateTime: item.dateTimeDisplay,
            description: item.title,
            excess: item.excess,
            index: index + 1,
            legalReference: item.legalReference,
            measured: item.measuredValue,
            severity: severityLabel(item.severity),
        })),
        introText: labels.statement,
        issuingCountry: model.issuingMemberState,
        issuingCountryLabel: labels.cardNumber,
        kind: 'infringementLetter',
        locale,
        measuredHeader: labels.colMeasured,
        numHeader: labels.colNum,
        operatorSignatureLabel: labels.managerSignature,
        severityHeader: labels.colSeverity,
        title: labels.title,
        totalInfringementsLabel: labels.totalInfringements,
        vehicleLabel: labels.vehicle,
        vehicleRegistration: model.vehicleRegistration ?? '',
        vin: model.vin ?? '',
        vinLabel,
    };
}

// Builds typed native PDF-engine request for EU attestation of activities form.
export function createAttestationFormPdfRequest(
    model: IAttestationFormViewModel,
    labels: IAttestationFormExportLabels,
    locale: string,
): IAttestationFormPdfRequest {
    const companyAddress =
        `${model.companyStreet}, ${model.companyPostalCode} ${model.companyCity}, ${model.companyCountry}`.trim();
    return {
        box10Label: labels.item10_licence,
        box11Label: labels.item11_employmentDate,
        box12Label: labels.item12_from,
        box13Label: labels.item13_to,
        box14Label: labels.item14_sickLeave,
        box15Label: labels.item15_annualLeave,
        box16Label: labels.item16_leaveOrRest,
        box17Label: labels.item17_outOfScope,
        box18Label: labels.item18_otherWork,
        box19Label: labels.item19_available,
        box1Label: labels.item1_undertaking,
        box20Label: labels.item20_place,
        box21Label: labels.item21_driverConfirm,
        box22Label: labels.item22_place,
        box2Label: labels.item2_address,
        box3Label: labels.item3_tel,
        box4Label: labels.item4_fax,
        box5Label: labels.item5_email,
        box6Label: labels.item6_name,
        box7Label: labels.item7_position,
        box8Label: labels.item8_driverName,
        box9Label: labels.item9_birthDate,
        companyAddress,
        companyEmail: model.companyEmail,
        companyFax: model.companyFax,
        companyName: model.companyName,
        companyPhone: model.companyTelephone,
        date: model.dateFormatted,
        dateLabel: labels.date,
        driverDob: model.driverBirthDate,
        driverName: model.driverName,
        driverPartTitle: labels.declareDriver,
        driverSignatureLabel: labels.driverSignature,
        drivingLicence: model.driverLicenceOrId,
        employmentStart: model.driverEmploymentDate,
        footnote: labels.footnote1,
        instructions: labels.officialInstruction,
        kind: 'attestationForm',
        locale,
        periodEnd: model.periodToFormatted,
        periodPartTitle: labels.forPeriod,
        periodStart: model.periodFromFormatted,
        place: model.companyCity,
        reasonKey: model.reason,
        signatoryName: model.managerName,
        signatoryPosition: model.managerPosition,
        signatureLabel: labels.signature,
        subtitle: labels.officialRegulation,
        title: labels.officialTitle,
        undersignedLabel: labels.undersigned,
        undertakingPartTitle: labels.partUndertaking,
        warning: labels.officialWarning,
    };
}
