export {
    APPLICATION_COMMANDS,
    decodeBinaryPayload,
    decodeReadTachographFileFailure,
    decodeRuntimeVersionsResult,
    decodeViewerPreferences,
    DEFAULT_VIEWER_PREFERENCES,
    DISABLED_APPLICATION_COMMAND_STATE,
    isNightWorkWindow,
    isSourceToken,
    isReopenToken,
    MAXIMUM_COLUMN_PREFERENCE_TABLES,
    MAXIMUM_GENERATED_BINARY_BYTES,
    MAXIMUM_OPEN_FILE_BYTES,
    MAXIMUM_PAGE_SIZE_PREFERENCE_TABLES,
    MAXIMUM_PINNED_COLUMNS_PER_TABLE,
    MAXIMUM_RECENT_FILES,
    NIGHT_WORK_WINDOW_LATEST_END_HOUR,
    NIGHT_WORK_WINDOW_MINIMUM_HOURS,
    type ApplicationCommand,
    type ApplicationCommandState,
    type DensityPreference,
    type DesktopOperationFailureCode,
    type CopyTextToClipboardResult,
    type ConvertHtmlToPdfResult,
    type GeneratedBinaryDocumentResult,
    type NativeCommandInvoker,
    type IOpenedTachographFile,
    type IOpenTachographPathRequest,
    type IRecentFileEntry,
    type IReleaseSourceRequest,
    type IRuntimeVersions,
    type ISaveExportRequest,
    type IViewerPreferences,
    type LoadPreferencesResult,
    type OpenTachographFileResult,
    type IReadTachographFileFailure,
    type RegisterExportSourceResult,
    type ReopenToken,
    type ReleaseSourceResult,
    type RuntimeVersionsResult,
    type SaveExportResult,
    type SavePreferencesResult,
    type SourceToken,
    type TablePageSize,
    type ThemePreference,
} from './desktop-api.js';
export { type ExportFailureCode } from './export-failure-code.js';
export {
    decodeErrorEvent,
    ERROR_CODES,
    type ErrorCode,
    type ErrorSeverity,
    type ErrorSource,
    type IErrorEvent,
    type ITranslationMissingKeyContext,
    type ITranslationMissingKeyErrorEvent,
} from './error-event.js';
export {
    decodeFileMetadata,
    isFileDisplayName,
    isSha256Digest,
    type FileDisplayName,
    type FileMetadataDecodeError,
    type IFileMetadata,
    type Sha256Digest,
} from './file-metadata.js';
export {
    type ParserDataFileSourcePaths,
    type ParserOutputVariant,
    type IParserVuVerificationSourcePaths,
} from './parser-shared.js';
export {
    classifyParseError,
    type ICancellationError,
    type IIntegrityLimitationError,
    type IInternalDefectError,
    type IParserFailureError,
    type IPlatformFailureError,
    type IUnsupportedDataError,
    type IUserCorrectableError,
    type ParseError,
    type ParseErrorCategory,
    type ParseFailureCode,
} from './error-taxonomy.js';
export { err, ok, type Result } from './result.js';
export {
    decodePdfDocumentRequest,
    type IActivitySegmentDto,
    type IActivityTimelineDayDto,
    type IAttestationFormPdfRequest,
    type IFactualReportPdfRequest,
    type IInfringementItemDto,
    type IInfringementLetterPdfRequest,
    type IPdfDocumentRequest,
    type IReportSummaryItemDto,
    type IReportTableRowDto,
    type IReportTableSectionDto,
    type PdfDocumentRequestDecodeError,
} from './pdf-document-request.js';
export { escapeHtml } from './html-escape.js';
export { fileNameSegment } from './file-name.js';
export {
    arrayOf,
    boundedString,
    exactRecord,
    hasExactKeys,
    isBoundaryRecord,
    isJsonValue,
    isNonNegativeSafeInteger,
    isString,
    isUnknownRecord,
    literal,
    nullable,
    type ExactRecordShape,
    type Guard,
    type IJsonRecord,
    type JsonValue,
    type UnknownRecord,
} from './unknown-value.js';
export {
    createMemoryKeyValueStore,
    createStoredValue,
    jsonStoredValueCodec,
    stringStoredValueCodec,
    type IKeyValueStore,
    type IStoredValue,
    type IStoredValueCodec,
} from './key-value-store.js';
