// Re-exports section view models to provide a single public presentation surface.
export {
    formattedValue,
    formatDateTime,
    formatDuration,
    formatNumber,
    formatUtcDate,
    formatUtcDateInputValue,
    formatUtcTime,
    type DocumentViewModelResult,
    type IFormattedUtcRange,
    type IFormattedValue,
} from '../helpers/view-model-formatting.js';
export {
    createDocumentContentCountsViewModel,
    createDocumentIntegrityOverviewViewModel,
    createDocumentOverviewViewModel,
    type ICardNotesViewModel,
    type IDocumentContentCountsViewModel,
    type IDocumentIntegrityOverviewViewModel,
    type IDocumentOverviewViewModel,
    type IDriverIdentityViewModel,
    type IdentityViewModel,
    type IVehicleIdentityViewModel,
} from './overview-view-model.js';
export {
    calculateDutyShifts,
    createActivitySectionViewModel,
    dutyShiftBelongsToUtcDay,
    getDutyShiftDayRelation,
    type DutyShiftDayRelation,
    type IActivityDayViewModel,
    type IActivityInfringementPinViewModel,
    type IActivityRecordViewModel,
    type IActivitySectionViewModel,
    type IActivityTimelineTickViewModel,
    type IActivityTotalsViewModel,
    type IContinuousDrivingProgressViewModel,
    type ActivityComplianceInput,
    type IActivityCreditedBreakViewModel,
    type IActivityRestWindowViewModel,
    type IDutyShiftCrewViewModel,
    type IDutyShiftViewModel,
} from './activity-view-model.js';
export {
    classifyEventFaultSecurity,
    createEventFaultSectionViewModel,
    type EventFaultSecurityCategory,
    type IEventFaultRecordViewModel,
    type IEventFaultSectionViewModel,
} from './event-fault-view-model.js';
export {
    createAssociationSectionViewModel,
    type AssociationRecordViewModel,
    type IAssociationSectionViewModel,
    type ICardUseViewModel,
    type IVehicleUnitUseViewModel,
    type IVehicleUseViewModel,
} from './association-view-model.js';
export {
    buildJourneyShifts,
    buildJourneySummary,
    createLocationSectionViewModel,
    journeyShiftBelongsToUtcDay,
    mapJourneyLegsToMapRoute,
    type IAccumulatedDrivingPositionViewModel,
    type IBorderCrossingViewModel,
    type IDailyWorkPeriodPlaceViewModel,
    type IGnssPositionEvidenceViewModel,
    type IJourneyLegCoordinates,
    type IJourneyLegViewModel,
    type IJourneyShiftSummary,
    type IJourneySummaryViewModel,
    type ILoadTypeEntryViewModel,
    type ILoadUnloadOperationViewModel,
    type ILocationSectionViewModel,
    type LocationRecordViewModel,
} from './location-view-model.js';
